_wandb:
    value:
        cli_version: 0.19.6
        m:
            - "1": val-Recall@1
              "6":
                - 3
              "7":
                - 2
        python_version: 3.13.0
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 63
                - 105
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 63
                - 105
            "3":
                - 2
                - 7
                - 13
                - 16
                - 23
                - 55
                - 62
                - 63
            "4": 3.13.0
            "5": 0.19.6
            "6": 4.48.2
            "8":
                - 1
                - 5
            "12": 0.19.6
            "13": linux-x86_64
alpha:
    value: 0
learning_rate:
    value: 5e-06
margin:
    value: 0.008726646259971648
training_intervention_fn:
    value: None
