#!/bin/bash
#SBATCH --job-name=cbm-reid-backbone
#SBATCH --partition=vision-beery
#SBATCH --qos=vision-beery-main
#SBATCH --account=vision-beery
##SBATCH --requeue

#SBATCH --time=7-0:00:00
#SBATCH --mem=64G
#SBATCH --gres=gpu:1
#SBATCH --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/backbone.%j.out
#SBATCH --chdir=/data/vision/beery/scratch/antoine/CBM_reid

set -euo pipefail

mkdir -p /data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs

# Main experiments ########################################################
# Finetuning triple-crop backbone on Mara : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name FinetuningTripleCropBackbone --epochs 300 --dataset mara --subset 2+encounters --backbone_pretraining savannah_elephants --backbone_lr 5e-6 --backbone_wd 1e-5 --print_every 5 --batch_size 64 --save_best True --wandb_group TripleCropBackbone_Mara --wandb_name TripleCropBackbone_finetuning_mara
# Finetuning triple-crop backbone on Mara from crop-specific MegaDescriptor gold weights : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name FinetuningTripleCropBackbone --epochs 300 --dataset mara --subset 2+encounters --backbone_pretraining MegaDescriptor_complete_gold,MegaDescriptor_left_gold,MegaDescriptor_right_gold --backbone_lr 5e-6 --backbone_wd 1e-5 --print_every 5 --batch_size 64 --save_best True --wandb_group TripleCropBackbone_Mara_MDgold --wandb_name TripleCropBackbone_finetuning_mara_from_MDgold
# Finetuning triple-crop backbone on Mara from scratch : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name FinetuningTripleCropBackbone --epochs 300 --dataset mara --subset 2+encounters --backbone_pretraining None --backbone_lr 5e-4 --backbone_wd 1e-5 --print_every 5 --batch_size 64 --save_best True --wandb_group TripleCropBackbone_Mara --wandb_name TripleCropBackbone_finetuning_mara_from_scratch
# Triple-crop backbone with normalization : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name FinetuningTripleCropBackbone --epochs 300 --dataset mara --subset 2+encounters --backbone_pretraining savannah_elephants --backbone_lr 5e-6 --backbone_wd 1e-5 --backbone_layer_norm True --print_every 5 --batch_size 64 --save_best True --wandb_group TripleCropBackbone_Mara --wandb_name TripleCropBackbone_finetuning_mara_layer_norm

# Sweep ########################################################
# Uncomment one line, then run `bash bash/backbone.sh` to launch one experiment.
# 01 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name FinetuningTripleCropBackbone --epochs 250 --dataset mara --subset 2+encounters --backbone_pretraining MegaDescriptor_complete_gold,MegaDescriptor_left_gold,MegaDescriptor_right_gold --backbone_lr 1e-3 --backbone_wd 1e-3 --print_every 5 --batch_size 64 --save_best True --wandb_group TripleCropBackbone_Mara_MDgold_sweep_e250 --wandb_name TCB_mara_MDgold_lr1e-3_wd1e-3_e250
# 02 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name FinetuningTripleCropBackbone --epochs 250 --dataset mara --subset 2+encounters --backbone_pretraining MegaDescriptor_complete_gold,MegaDescriptor_left_gold,MegaDescriptor_right_gold --backbone_lr 1e-3 --backbone_wd 1e-4 --print_every 5 --batch_size 64 --save_best True --wandb_group TripleCropBackbone_Mara_MDgold_sweep_e250 --wandb_name TCB_mara_MDgold_lr1e-3_wd1e-4_e250
# 03 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name FinetuningTripleCropBackbone --epochs 250 --dataset mara --subset 2+encounters --backbone_pretraining MegaDescriptor_complete_gold,MegaDescriptor_left_gold,MegaDescriptor_right_gold --backbone_lr 1e-3 --backbone_wd 1e-5 --print_every 5 --batch_size 64 --save_best True --wandb_group TripleCropBackbone_Mara_MDgold_sweep_e250 --wandb_name TCB_mara_MDgold_lr1e-3_wd1e-5_e250
# 04 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name FinetuningTripleCropBackbone --epochs 250 --dataset mara --subset 2+encounters --backbone_pretraining MegaDescriptor_complete_gold,MegaDescriptor_left_gold,MegaDescriptor_right_gold --backbone_lr 1e-3 --backbone_wd 1e-6 --print_every 5 --batch_size 64 --save_best True --wandb_group TripleCropBackbone_Mara_MDgold_sweep_e250 --wandb_name TCB_mara_MDgold_lr1e-3_wd1e-6_e250
# 05 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name FinetuningTripleCropBackbone --epochs 250 --dataset mara --subset 2+encounters --backbone_pretraining MegaDescriptor_complete_gold,MegaDescriptor_left_gold,MegaDescriptor_right_gold --backbone_lr 1e-4 --backbone_wd 1e-3 --print_every 5 --batch_size 64 --save_best True --wandb_group TripleCropBackbone_Mara_MDgold_sweep_e250 --wandb_name TCB_mara_MDgold_lr1e-4_wd1e-3_e250
# 06 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name FinetuningTripleCropBackbone --epochs 250 --dataset mara --subset 2+encounters --backbone_pretraining MegaDescriptor_complete_gold,MegaDescriptor_left_gold,MegaDescriptor_right_gold --backbone_lr 1e-4 --backbone_wd 1e-4 --print_every 5 --batch_size 64 --save_best True --wandb_group TripleCropBackbone_Mara_MDgold_sweep_e250 --wandb_name TCB_mara_MDgold_lr1e-4_wd1e-4_e250
# 07 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name FinetuningTripleCropBackbone --epochs 250 --dataset mara --subset 2+encounters --backbone_pretraining MegaDescriptor_complete_gold,MegaDescriptor_left_gold,MegaDescriptor_right_gold --backbone_lr 1e-4 --backbone_wd 1e-5 --print_every 5 --batch_size 64 --save_best True --wandb_group TripleCropBackbone_Mara_MDgold_sweep_e250 --wandb_name TCB_mara_MDgold_lr1e-4_wd1e-5_e250
# 08 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name FinetuningTripleCropBackbone --epochs 250 --dataset mara --subset 2+encounters --backbone_pretraining MegaDescriptor_complete_gold,MegaDescriptor_left_gold,MegaDescriptor_right_gold --backbone_lr 1e-4 --backbone_wd 1e-6 --print_every 5 --batch_size 64 --save_best True --wandb_group TripleCropBackbone_Mara_MDgold_sweep_e250 --wandb_name TCB_mara_MDgold_lr1e-4_wd1e-6_e250
# 09 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name FinetuningTripleCropBackbone --epochs 250 --dataset mara --subset 2+encounters --backbone_pretraining MegaDescriptor_complete_gold,MegaDescriptor_left_gold,MegaDescriptor_right_gold --backbone_lr 1e-5 --backbone_wd 1e-3 --print_every 5 --batch_size 64 --save_best True --wandb_group TripleCropBackbone_Mara_MDgold_sweep_e250 --wandb_name TCB_mara_MDgold_lr1e-5_wd1e-3_e250
# 10 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name FinetuningTripleCropBackbone --epochs 250 --dataset mara --subset 2+encounters --backbone_pretraining MegaDescriptor_complete_gold,MegaDescriptor_left_gold,MegaDescriptor_right_gold --backbone_lr 1e-5 --backbone_wd 1e-4 --print_every 5 --batch_size 64 --save_best True --wandb_group TripleCropBackbone_Mara_MDgold_sweep_e250 --wandb_name TCB_mara_MDgold_lr1e-5_wd1e-4_e250
# 11 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name FinetuningTripleCropBackbone --epochs 250 --dataset mara --subset 2+encounters --backbone_pretraining MegaDescriptor_complete_gold,MegaDescriptor_left_gold,MegaDescriptor_right_gold --backbone_lr 1e-5 --backbone_wd 1e-5 --print_every 5 --batch_size 64 --save_best True --wandb_group TripleCropBackbone_Mara_MDgold_sweep_e250 --wandb_name TCB_mara_MDgold_lr1e-5_wd1e-5_e250
# 12 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name FinetuningTripleCropBackbone --epochs 250 --dataset mara --subset 2+encounters --backbone_pretraining MegaDescriptor_complete_gold,MegaDescriptor_left_gold,MegaDescriptor_right_gold --backbone_lr 1e-5 --backbone_wd 1e-6 --print_every 5 --batch_size 64 --save_best True --wandb_group TripleCropBackbone_Mara_MDgold_sweep_e250 --wandb_name TCB_mara_MDgold_lr1e-5_wd1e-6_e250
# 13 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name FinetuningTripleCropBackbone --epochs 250 --dataset mara --subset 2+encounters --backbone_pretraining MegaDescriptor_complete_gold,MegaDescriptor_left_gold,MegaDescriptor_right_gold --backbone_lr 1e-6 --backbone_wd 1e-3 --print_every 5 --batch_size 64 --save_best True --wandb_group TripleCropBackbone_Mara_MDgold_sweep_e250 --wandb_name TCB_mara_MDgold_lr1e-6_wd1e-3_e250
# 14 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name FinetuningTripleCropBackbone --epochs 250 --dataset mara --subset 2+encounters --backbone_pretraining MegaDescriptor_complete_gold,MegaDescriptor_left_gold,MegaDescriptor_right_gold --backbone_lr 1e-6 --backbone_wd 1e-4 --print_every 5 --batch_size 64 --save_best True --wandb_group TripleCropBackbone_Mara_MDgold_sweep_e250 --wandb_name TCB_mara_MDgold_lr1e-6_wd1e-4_e250
# 15 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name FinetuningTripleCropBackbone --epochs 250 --dataset mara --subset 2+encounters --backbone_pretraining MegaDescriptor_complete_gold,MegaDescriptor_left_gold,MegaDescriptor_right_gold --backbone_lr 1e-6 --backbone_wd 1e-5 --print_every 5 --batch_size 64 --save_best True --wandb_group TripleCropBackbone_Mara_MDgold_sweep_e250 --wandb_name TCB_mara_MDgold_lr1e-6_wd1e-5_e250
# 16 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name FinetuningTripleCropBackbone --epochs 250 --dataset mara --subset 2+encounters --backbone_pretraining MegaDescriptor_complete_gold,MegaDescriptor_left_gold,MegaDescriptor_right_gold --backbone_lr 1e-6 --backbone_wd 1e-6 --print_every 5 --batch_size 64 --save_best True --wandb_group TripleCropBackbone_Mara_MDgold_sweep_e250 --wandb_name TCB_mara_MDgold_lr1e-6_wd1e-6_e250
# 17 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name FinetuningTripleCropBackbone --epochs 250 --dataset mara --subset 2+encounters --backbone_pretraining MegaDescriptor_complete_gold,MegaDescriptor_left_gold,MegaDescriptor_right_gold --backbone_lr 1e-7 --backbone_wd 1e-3 --print_every 5 --batch_size 64 --save_best True --wandb_group TripleCropBackbone_Mara_MDgold_sweep_e250 --wandb_name TCB_mara_MDgold_lr1e-7_wd1e-3_e250
# 18 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name FinetuningTripleCropBackbone --epochs 250 --dataset mara --subset 2+encounters --backbone_pretraining MegaDescriptor_complete_gold,MegaDescriptor_left_gold,MegaDescriptor_right_gold --backbone_lr 1e-7 --backbone_wd 1e-4 --print_every 5 --batch_size 64 --save_best True --wandb_group TripleCropBackbone_Mara_MDgold_sweep_e250 --wandb_name TCB_mara_MDgold_lr1e-7_wd1e-4_e250
# 19 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name FinetuningTripleCropBackbone --epochs 250 --dataset mara --subset 2+encounters --backbone_pretraining MegaDescriptor_complete_gold,MegaDescriptor_left_gold,MegaDescriptor_right_gold --backbone_lr 1e-7 --backbone_wd 1e-5 --print_every 5 --batch_size 64 --save_best True --wandb_group TripleCropBackbone_Mara_MDgold_sweep_e250 --wandb_name TCB_mara_MDgold_lr1e-7_wd1e-5_e250
# 20 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name FinetuningTripleCropBackbone --epochs 250 --dataset mara --subset 2+encounters --backbone_pretraining MegaDescriptor_complete_gold,MegaDescriptor_left_gold,MegaDescriptor_right_gold --backbone_lr 1e-7 --backbone_wd 1e-6 --print_every 5 --batch_size 64 --save_best True --wandb_group TripleCropBackbone_Mara_MDgold_sweep_e250 --wandb_name TCB_mara_MDgold_lr1e-7_wd1e-6_e250
