#!/bin/bash
#SBATCH --job-name=cbm-reid-concept-head
#SBATCH --partition=vision-beery
#SBATCH --qos=vision-beery-main
#SBATCH --account=vision-beery
##SBATCH --requeue

#SBATCH --time=2-0:00:00
#SBATCH --mem=64G
#SBATCH --gres=gpu:1
#SBATCH --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/concept_head.%j.out
#SBATCH --chdir=/data/vision/beery/scratch/antoine/CBM_reid

set -euo pipefail

mkdir -p /data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs
mkdir -p /data/vision/beery/scratch/antoine/CBM_reid/experiments/wandb /data/vision/beery/scratch/antoine/CBM_reid/experiments/wandb-cache


# Sweep for finetuning ########################################################
# 01 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name TrainingConceptHead --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining MegaDescriptor_complete_gold,MegaDescriptor_left_gold,MegaDescriptor_right_gold --concept_head_pretraining None --concept_head_lr 2e-6 --concept_head_wd 1e-5 --concept_head_target_is_ele_seek False --concept_head_training finetuning --print_every 5 --batch_size 64 --save_best True --wandb_group ConceptHead_MDgold_finetuning_sweep --wandb_name ConceptHead_finetuning_subject_lr2e-6_wd1e-5_MDgold
# 02 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name TrainingConceptHead --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining MegaDescriptor_complete_gold,MegaDescriptor_left_gold,MegaDescriptor_right_gold --concept_head_pretraining None --concept_head_lr 2e-6 --concept_head_wd 1e-6 --concept_head_target_is_ele_seek False --concept_head_training finetuning --print_every 5 --batch_size 64 --save_best True --wandb_group ConceptHead_MDgold_finetuning_sweep --wandb_name ConceptHead_finetuning_subject_lr2e-6_wd1e-6_MDgold
# 03 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name TrainingConceptHead --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining MegaDescriptor_complete_gold,MegaDescriptor_left_gold,MegaDescriptor_right_gold --concept_head_pretraining None --concept_head_lr 2e-6 --concept_head_wd 1e-7 --concept_head_target_is_ele_seek False --concept_head_training finetuning --print_every 5 --batch_size 64 --save_best True --wandb_group ConceptHead_MDgold_finetuning_sweep --wandb_name ConceptHead_finetuning_subject_lr2e-6_wd1e-7_MDgold
# 04 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name TrainingConceptHead --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining MegaDescriptor_complete_gold,MegaDescriptor_left_gold,MegaDescriptor_right_gold --concept_head_pretraining None --concept_head_lr 1e-6 --concept_head_wd 1e-5 --concept_head_target_is_ele_seek False --concept_head_training finetuning --print_every 5 --batch_size 64 --save_best True --wandb_group ConceptHead_MDgold_finetuning_sweep --wandb_name ConceptHead_finetuning_subject_lr1e-6_wd1e-5_MDgold
# 05 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name TrainingConceptHead --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining MegaDescriptor_complete_gold,MegaDescriptor_left_gold,MegaDescriptor_right_gold --concept_head_pretraining None --concept_head_lr 1e-6 --concept_head_wd 1e-6 --concept_head_target_is_ele_seek False --concept_head_training finetuning --print_every 5 --batch_size 64 --save_best True --wandb_group ConceptHead_MDgold_finetuning_sweep --wandb_name ConceptHead_finetuning_subject_lr1e-6_wd1e-6_MDgold
# 06 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name TrainingConceptHead --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining MegaDescriptor_complete_gold,MegaDescriptor_left_gold,MegaDescriptor_right_gold --concept_head_pretraining None --concept_head_lr 1e-6 --concept_head_wd 1e-7 --concept_head_target_is_ele_seek False --concept_head_training finetuning --print_every 5 --batch_size 64 --save_best True --wandb_group ConceptHead_MDgold_finetuning_sweep --wandb_name ConceptHead_finetuning_subject_lr1e-6_wd1e-7_MDgold
# 07 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name TrainingConceptHead --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining MegaDescriptor_complete_gold,MegaDescriptor_left_gold,MegaDescriptor_right_gold --concept_head_pretraining None --concept_head_lr 5e-7 --concept_head_wd 1e-5 --concept_head_target_is_ele_seek False --concept_head_training finetuning --print_every 5 --batch_size 64 --save_best True --wandb_group ConceptHead_MDgold_finetuning_sweep --wandb_name ConceptHead_finetuning_subject_lr5e-7_wd1e-5_MDgold
# 08 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name TrainingConceptHead --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining MegaDescriptor_complete_gold,MegaDescriptor_left_gold,MegaDescriptor_right_gold --concept_head_pretraining None --concept_head_lr 5e-7 --concept_head_wd 1e-6 --concept_head_target_is_ele_seek False --concept_head_training finetuning --print_every 5 --batch_size 64 --save_best True --wandb_group ConceptHead_MDgold_finetuning_sweep --wandb_name ConceptHead_finetuning_subject_lr5e-7_wd1e-6_MDgold
# 09 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name TrainingConceptHead --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining MegaDescriptor_complete_gold,MegaDescriptor_left_gold,MegaDescriptor_right_gold --concept_head_pretraining None --concept_head_lr 5e-7 --concept_head_wd 1e-7 --concept_head_target_is_ele_seek False --concept_head_training finetuning --print_every 5 --batch_size 64 --save_best True --wandb_group ConceptHead_MDgold_finetuning_sweep --wandb_name ConceptHead_finetuning_subject_lr5e-7_wd1e-7_MDgold

# sweep for probing ########################################################
# 01 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name TrainingConceptHead --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining MegaDescriptor_complete_gold,MegaDescriptor_left_gold,MegaDescriptor_right_gold --concept_head_pretraining None --concept_head_lr 2e-5 --concept_head_wd 1e-4 --concept_head_target_is_ele_seek False --concept_head_training probing --print_every 5 --batch_size 64 --save_best True --wandb_group ConceptHead_MDgold_probing_sweep --wandb_name ConceptHead_probing_subject_lr2e-5_wd1e-4_MDgold
# 02 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name TrainingConceptHead --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining MegaDescriptor_complete_gold,MegaDescriptor_left_gold,MegaDescriptor_right_gold --concept_head_pretraining None --concept_head_lr 2e-5 --concept_head_wd 1e-5 --concept_head_target_is_ele_seek False --concept_head_training probing --print_every 5 --batch_size 64 --save_best True --wandb_group ConceptHead_MDgold_probing_sweep --wandb_name ConceptHead_probing_subject_lr2e-5_wd1e-5_MDgold
# 03 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name TrainingConceptHead --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining MegaDescriptor_complete_gold,MegaDescriptor_left_gold,MegaDescriptor_right_gold --concept_head_pretraining None --concept_head_lr 2e-5 --concept_head_wd 1e-6 --concept_head_target_is_ele_seek False --concept_head_training probing --print_every 5 --batch_size 64 --save_best True --wandb_group ConceptHead_MDgold_probing_sweep --wandb_name ConceptHead_probing_subject_lr2e-5_wd1e-6_MDgold
# 04 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name TrainingConceptHead --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining MegaDescriptor_complete_gold,MegaDescriptor_left_gold,MegaDescriptor_right_gold --concept_head_pretraining None --concept_head_lr 1e-5 --concept_head_wd 1e-4 --concept_head_target_is_ele_seek False --concept_head_training probing --print_every 5 --batch_size 64 --save_best True --wandb_group ConceptHead_MDgold_probing_sweep --wandb_name ConceptHead_probing_subject_lr1e-5_wd1e-4_MDgold
# 05 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name TrainingConceptHead --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining MegaDescriptor_complete_gold,MegaDescriptor_left_gold,MegaDescriptor_right_gold --concept_head_pretraining None --concept_head_lr 1e-5 --concept_head_wd 1e-5 --concept_head_target_is_ele_seek False --concept_head_training probing --print_every 5 --batch_size 64 --save_best True --wandb_group ConceptHead_MDgold_probing_sweep --wandb_name ConceptHead_probing_subject_lr1e-5_wd1e-5_MDgold
# 06 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name TrainingConceptHead --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining MegaDescriptor_complete_gold,MegaDescriptor_left_gold,MegaDescriptor_right_gold --concept_head_pretraining None --concept_head_lr 1e-5 --concept_head_wd 1e-6 --concept_head_target_is_ele_seek False --concept_head_training probing --print_every 5 --batch_size 64 --save_best True --wandb_group ConceptHead_MDgold_probing_sweep --wandb_name ConceptHead_probing_subject_lr1e-5_wd1e-6_MDgold
# 07 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name TrainingConceptHead --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining MegaDescriptor_complete_gold,MegaDescriptor_left_gold,MegaDescriptor_right_gold --concept_head_pretraining None --concept_head_lr 5e-6 --concept_head_wd 1e-4 --concept_head_target_is_ele_seek False --concept_head_training probing --print_every 5 --batch_size 64 --save_best True --wandb_group ConceptHead_MDgold_probing_sweep --wandb_name ConceptHead_probing_subject_lr5e-6_wd1e-4_MDgold
# 08 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name TrainingConceptHead --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining MegaDescriptor_complete_gold,MegaDescriptor_left_gold,MegaDescriptor_right_gold --concept_head_pretraining None --concept_head_lr 5e-6 --concept_head_wd 1e-5 --concept_head_target_is_ele_seek False --concept_head_training probing --print_every 5 --batch_size 64 --save_best True --wandb_group ConceptHead_MDgold_probing_sweep --wandb_name ConceptHead_probing_subject_lr5e-6_wd1e-5_MDgold
# 09 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name TrainingConceptHead --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining MegaDescriptor_complete_gold,MegaDescriptor_left_gold,MegaDescriptor_right_gold --concept_head_pretraining None --concept_head_lr 5e-6 --concept_head_wd 1e-6 --concept_head_target_is_ele_seek False --concept_head_training probing --print_every 5 --batch_size 64 --save_best True --wandb_group ConceptHead_MDgold_probing_sweep --wandb_name ConceptHead_probing_subject_lr5e-6_wd1e-6_MDgold

# Selected hparams from completed sweep runs:
# finetuning: lr=2e-6, wd=1e-6 
# probing: lr=2e-5, wd=1e-4 

# Architecture comparison on the selected finetuning setting ########################################################
# crossed : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name TrainingConceptHead --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining MegaDescriptor_complete_gold,MegaDescriptor_left_gold,MegaDescriptor_right_gold --concept_head_pretraining None --concept_head_architecture crossed --concept_head_lr 2e-6 --concept_head_wd 1e-6 --concept_head_target_is_ele_seek False --concept_head_training finetuning --print_every 5 --batch_size 64 --save_best True --wandb_group ConceptHead_architecture_compare_MDgold --wandb_name ConceptHead_crossed_finetuning_subject_lr2e-6_wd1e-6_MDgold
# multi : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name TrainingConceptHead --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining MegaDescriptor_complete_gold,MegaDescriptor_left_gold,MegaDescriptor_right_gold --concept_head_pretraining None --concept_head_architecture multi --concept_head_lr 2e-6 --concept_head_wd 1e-6 --concept_head_target_is_ele_seek False --concept_head_training finetuning --print_every 5 --batch_size 64 --save_best True --wandb_group ConceptHead_architecture_compare_MDgold --wandb_name ConceptHead_multi_finetuning_subject_lr2e-6_wd1e-6_MDgold
# three : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name TrainingConceptHead --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining MegaDescriptor_complete_gold,MegaDescriptor_left_gold,MegaDescriptor_right_gold --concept_head_pretraining None --concept_head_architecture three --concept_head_lr 2e-6 --concept_head_wd 1e-6 --concept_head_target_is_ele_seek False --concept_head_training finetuning --print_every 5 --batch_size 64 --save_best True --wandb_group ConceptHead_architecture_compare_MDgold --wandb_name ConceptHead_three_finetuning_subject_lr2e-6_wd1e-6_MDgold

# Main experiments from MegaDescriptor gold ########################################################
# finetune + subject : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name TrainingConceptHead --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining MegaDescriptor_complete_gold,MegaDescriptor_left_gold,MegaDescriptor_right_gold --concept_head_pretraining None --concept_head_architecture three --concept_head_lr 2e-6 --concept_head_wd 1e-6 --concept_head_target_is_ele_seek False --concept_head_training finetuning --print_every 5 --batch_size 64 --save_best True --wandb_group ConceptHead_ablation --wandb_name ConceptHead_finetuning_on_subject
# finetune + ele : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name TrainingConceptHead --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining MegaDescriptor_complete_gold,MegaDescriptor_left_gold,MegaDescriptor_right_gold --concept_head_pretraining None --concept_head_architecture three --concept_head_lr 2e-6 --concept_head_wd 1e-6 --concept_head_target_is_ele_seek True --concept_head_training finetuning --print_every 5 --batch_size 64 --save_best True --wandb_group ConceptHead_ablation --wandb_name ConceptHead_finetuning_on_ele
# probing + subject : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name TrainingConceptHead --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining MegaDescriptor_complete_gold,MegaDescriptor_left_gold,MegaDescriptor_right_gold --concept_head_pretraining None --concept_head_architecture three --concept_head_lr 2e-5 --concept_head_wd 1e-4 --concept_head_target_is_ele_seek False --concept_head_training probing --print_every 5 --batch_size 64 --save_best True --wandb_group ConceptHead_ablation --wandb_name ConceptHead_probing_on_subject
# probing + ele : 
python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name TrainingConceptHead --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining MegaDescriptor_complete_gold,MegaDescriptor_left_gold,MegaDescriptor_right_gold --concept_head_pretraining None --concept_head_architecture three --concept_head_lr 2e-5 --concept_head_wd 1e-4 --concept_head_target_is_ele_seek True --concept_head_training probing --print_every 5 --batch_size 64 --save_best True --wandb_group ConceptHead_ablation --wandb_name ConceptHead_probing_on_ele

# Golden ?? ########################################################
