#!/bin/bash
#SBATCH --job-name=cbm-reid-megadescriptor
#SBATCH --partition=vision-beery
#SBATCH --qos=vision-beery-main
#SBATCH --account=vision-beery
##SBATCH --requeue

#SBATCH --time=7-0:00:00
#SBATCH --mem=64G
#SBATCH --gres=gpu:1
#SBATCH --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/mega_descriptor.%j.out
#SBATCH --chdir=/data/vision/beery/scratch/antoine/CBM_reid

set -euo pipefail

mkdir -p /data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs

# Main experiments ########################################################
# Zero-shot MegaDescriptor on the complete crop : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name PretrainMegaDescriptor --mega_descriptor_mode zero_shot --mega_descriptor_crop complete --dataset mara --subset 2+encounters --batch_size 64 --print_every 5 --wandb_group MegaDescriptor_Mara_complete --wandb_name MegaDescriptor_zero_shot_mara_complete
# Savannah elephants MegaDescriptor on the complete crop : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name PretrainMegaDescriptor --mega_descriptor_mode savannah_elephants --mega_descriptor_crop complete --dataset mara --subset 2+encounters --batch_size 64 --print_every 5 --wandb_group MegaDescriptor_Mara_complete --wandb_name MegaDescriptor_savannah_elephants_mara_complete
# Finetuning MegaDescriptor on Mara with the complete crop : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name PretrainMegaDescriptor --mega_descriptor_mode finetuning --mega_descriptor_crop complete --epochs 300 --dataset mara --subset 2+encounters --backbone_pretraining savannah_elephants --backbone_lr 1e-4 --backbone_wd 1e-5 --print_every 5 --batch_size 64 --wandb_group MegaDescriptor_Mara_complete --wandb_name MegaDescriptor_finetuning_mara_complete
# Finetuning MegaDescriptor on Mara with the left ear crop : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name PretrainMegaDescriptor --mega_descriptor_mode finetuning --mega_descriptor_crop left_ear --epochs 300 --dataset mara --subset 2+encounters --backbone_pretraining savannah_elephants --backbone_lr 1e-4 --backbone_wd 1e-5 --print_every 5 --batch_size 64 --wandb_group MegaDescriptor_Mara_left_ear --wandb_name MegaDescriptor_finetuning_mara_left_ear
# Finetuning MegaDescriptor on Mara with the right ear crop : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name PretrainMegaDescriptor --mega_descriptor_mode finetuning --mega_descriptor_crop right_ear --epochs 300 --dataset mara --subset 2+encounters --backbone_pretraining savannah_elephants --backbone_lr 1e-5 --backbone_wd 1e-4 --print_every 5 --batch_size 64 --wandb_group MegaDescriptor_Mara_right_ear --wandb_name MegaDescriptor_finetuning_mara_right_ear

# MiewID baselines ########################################################
# Out-of-box MiewID : sbatch --parsable --job-name=MiewID_oob --partition=vision-beery --qos=vision-beery-main --account=vision-beery --time=7-0:00:00 --mem=64G --gres=gpu:1 --chdir=/data/vision/beery/scratch/antoine/CBM_reid --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/MiewID_out_of_box.%j.out --wrap="python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name MiewID --miewid_mode out_of_box --dataset mara --subset 2+encounters --batch_size 64 --print_every 5 --wandb_group MiewID_Mara --wandb_name MiewID_out_of_box_mara"
# Finetuned MiewID : sbatch --parsable --job-name=MiewID_ft --partition=vision-beery --qos=vision-beery-main --account=vision-beery --time=7-0:00:00 --mem=64G --gres=gpu:1 --chdir=/data/vision/beery/scratch/antoine/CBM_reid --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/MiewID_finetuned.%j.out --wrap="python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name MiewID --miewid_mode finetuning --epochs 200 --dataset mara --subset 2+encounters --backbone_pretraining out_of_box --backbone_lr 1e-5 --backbone_wd 1e-5 --print_every 5 --batch_size 64 --wandb_group MiewID_Mara --wandb_name MiewID_finetuned_mara_lr1e-5_wd1e-5_e200"

# Sweep ########################################################
# Uncomment one line, then run `bash bash/mega_descriptor.sh` to submit exactly one Slurm job.

# Complete crop
# 01 : sbatch --parsable --job-name=MDc_01 --partition=vision-beery --qos=vision-beery-main --account=vision-beery --time=7-0:00:00 --mem=64G --gres=gpu:1 --chdir=/data/vision/beery/scratch/antoine/CBM_reid --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/MD_mara_complete_lr1e-2_wd1e-3_e200.%j.out --wrap="python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name PretrainMegaDescriptor --mega_descriptor_mode finetuning --mega_descriptor_crop complete --epochs 200 --dataset mara --subset 2+encounters --backbone_pretraining savannah_elephants --backbone_lr 1e-2 --backbone_wd 1e-3 --print_every 5 --batch_size 64 --wandb_group MegaDescriptor_Mara_complete_sweep --wandb_name MD_mara_complete_lr1e-2_wd1e-3_e200"
# 02 : sbatch --parsable --job-name=MDc_02 --partition=vision-beery --qos=vision-beery-main --account=vision-beery --time=7-0:00:00 --mem=64G --gres=gpu:1 --chdir=/data/vision/beery/scratch/antoine/CBM_reid --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/MD_mara_complete_lr1e-2_wd1e-4_e200.%j.out --wrap="python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name PretrainMegaDescriptor --mega_descriptor_mode finetuning --mega_descriptor_crop complete --epochs 200 --dataset mara --subset 2+encounters --backbone_pretraining savannah_elephants --backbone_lr 1e-2 --backbone_wd 1e-4 --print_every 5 --batch_size 64 --wandb_group MegaDescriptor_Mara_complete_sweep --wandb_name MD_mara_complete_lr1e-2_wd1e-4_e200"
# 03 : sbatch --parsable --job-name=MDc_03 --partition=vision-beery --qos=vision-beery-main --account=vision-beery --time=7-0:00:00 --mem=64G --gres=gpu:1 --chdir=/data/vision/beery/scratch/antoine/CBM_reid --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/MD_mara_complete_lr1e-2_wd1e-5_e200.%j.out --wrap="python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name PretrainMegaDescriptor --mega_descriptor_mode finetuning --mega_descriptor_crop complete --epochs 200 --dataset mara --subset 2+encounters --backbone_pretraining savannah_elephants --backbone_lr 1e-2 --backbone_wd 1e-5 --print_every 5 --batch_size 64 --wandb_group MegaDescriptor_Mara_complete_sweep --wandb_name MD_mara_complete_lr1e-2_wd1e-5_e200"
# 04 : sbatch --parsable --job-name=MDc_04 --partition=vision-beery --qos=vision-beery-main --account=vision-beery --time=7-0:00:00 --mem=64G --gres=gpu:1 --chdir=/data/vision/beery/scratch/antoine/CBM_reid --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/MD_mara_complete_lr1e-2_wd1e-6_e200.%j.out --wrap="python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name PretrainMegaDescriptor --mega_descriptor_mode finetuning --mega_descriptor_crop complete --epochs 200 --dataset mara --subset 2+encounters --backbone_pretraining savannah_elephants --backbone_lr 1e-2 --backbone_wd 1e-6 --print_every 5 --batch_size 64 --wandb_group MegaDescriptor_Mara_complete_sweep --wandb_name MD_mara_complete_lr1e-2_wd1e-6_e200"
# 05 : sbatch --parsable --job-name=MDc_05 --partition=vision-beery --qos=vision-beery-main --account=vision-beery --time=7-0:00:00 --mem=64G --gres=gpu:1 --chdir=/data/vision/beery/scratch/antoine/CBM_reid --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/MD_mara_complete_lr1e-3_wd1e-3_e200.%j.out --wrap="python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name PretrainMegaDescriptor --mega_descriptor_mode finetuning --mega_descriptor_crop complete --epochs 200 --dataset mara --subset 2+encounters --backbone_pretraining savannah_elephants --backbone_lr 1e-3 --backbone_wd 1e-3 --print_every 5 --batch_size 64 --wandb_group MegaDescriptor_Mara_complete_sweep --wandb_name MD_mara_complete_lr1e-3_wd1e-3_e200"
# 06 : sbatch --parsable --job-name=MDc_06 --partition=vision-beery --qos=vision-beery-main --account=vision-beery --time=7-0:00:00 --mem=64G --gres=gpu:1 --chdir=/data/vision/beery/scratch/antoine/CBM_reid --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/MD_mara_complete_lr1e-3_wd1e-4_e200.%j.out --wrap="python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name PretrainMegaDescriptor --mega_descriptor_mode finetuning --mega_descriptor_crop complete --epochs 200 --dataset mara --subset 2+encounters --backbone_pretraining savannah_elephants --backbone_lr 1e-3 --backbone_wd 1e-4 --print_every 5 --batch_size 64 --wandb_group MegaDescriptor_Mara_complete_sweep --wandb_name MD_mara_complete_lr1e-3_wd1e-4_e200"
# 07 : sbatch --parsable --job-name=MDc_07 --partition=vision-beery --qos=vision-beery-main --account=vision-beery --time=7-0:00:00 --mem=64G --gres=gpu:1 --chdir=/data/vision/beery/scratch/antoine/CBM_reid --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/MD_mara_complete_lr1e-3_wd1e-5_e200.%j.out --wrap="python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name PretrainMegaDescriptor --mega_descriptor_mode finetuning --mega_descriptor_crop complete --epochs 200 --dataset mara --subset 2+encounters --backbone_pretraining savannah_elephants --backbone_lr 1e-3 --backbone_wd 1e-5 --print_every 5 --batch_size 64 --wandb_group MegaDescriptor_Mara_complete_sweep --wandb_name MD_mara_complete_lr1e-3_wd1e-5_e200"
# 08 : sbatch --parsable --job-name=MDc_08 --partition=vision-beery --qos=vision-beery-main --account=vision-beery --time=7-0:00:00 --mem=64G --gres=gpu:1 --chdir=/data/vision/beery/scratch/antoine/CBM_reid --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/MD_mara_complete_lr1e-3_wd1e-6_e200.%j.out --wrap="python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name PretrainMegaDescriptor --mega_descriptor_mode finetuning --mega_descriptor_crop complete --epochs 200 --dataset mara --subset 2+encounters --backbone_pretraining savannah_elephants --backbone_lr 1e-3 --backbone_wd 1e-6 --print_every 5 --batch_size 64 --wandb_group MegaDescriptor_Mara_complete_sweep --wandb_name MD_mara_complete_lr1e-3_wd1e-6_e200"
# 09 : sbatch --parsable --job-name=MDc_09 --partition=vision-beery --qos=vision-beery-main --account=vision-beery --time=7-0:00:00 --mem=64G --gres=gpu:1 --chdir=/data/vision/beery/scratch/antoine/CBM_reid --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/MD_mara_complete_lr1e-4_wd1e-3_e200.%j.out --wrap="python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name PretrainMegaDescriptor --mega_descriptor_mode finetuning --mega_descriptor_crop complete --epochs 200 --dataset mara --subset 2+encounters --backbone_pretraining savannah_elephants --backbone_lr 1e-4 --backbone_wd 1e-3 --print_every 5 --batch_size 64 --wandb_group MegaDescriptor_Mara_complete_sweep --wandb_name MD_mara_complete_lr1e-4_wd1e-3_e200"
# 10 : sbatch --parsable --job-name=MDc_10 --partition=vision-beery --qos=vision-beery-main --account=vision-beery --time=7-0:00:00 --mem=64G --gres=gpu:1 --chdir=/data/vision/beery/scratch/antoine/CBM_reid --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/MD_mara_complete_lr1e-4_wd1e-4_e200.%j.out --wrap="python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name PretrainMegaDescriptor --mega_descriptor_mode finetuning --mega_descriptor_crop complete --epochs 200 --dataset mara --subset 2+encounters --backbone_pretraining savannah_elephants --backbone_lr 1e-4 --backbone_wd 1e-4 --print_every 5 --batch_size 64 --wandb_group MegaDescriptor_Mara_complete_sweep --wandb_name MD_mara_complete_lr1e-4_wd1e-4_e200"
# 11 : sbatch --parsable --job-name=MDc_11 --partition=vision-beery --qos=vision-beery-main --account=vision-beery --time=7-0:00:00 --mem=64G --gres=gpu:1 --chdir=/data/vision/beery/scratch/antoine/CBM_reid --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/MD_mara_complete_lr1e-4_wd1e-5_e200.%j.out --wrap="python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name PretrainMegaDescriptor --mega_descriptor_mode finetuning --mega_descriptor_crop complete --epochs 200 --dataset mara --subset 2+encounters --backbone_pretraining savannah_elephants --backbone_lr 1e-4 --backbone_wd 1e-5 --print_every 5 --batch_size 64 --wandb_group MegaDescriptor_Mara_complete_sweep --wandb_name MD_mara_complete_lr1e-4_wd1e-5_e200"
# 12 : sbatch --parsable --job-name=MDc_12 --partition=vision-beery --qos=vision-beery-main --account=vision-beery --time=7-0:00:00 --mem=64G --gres=gpu:1 --chdir=/data/vision/beery/scratch/antoine/CBM_reid --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/MD_mara_complete_lr1e-4_wd1e-6_e200.%j.out --wrap="python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name PretrainMegaDescriptor --mega_descriptor_mode finetuning --mega_descriptor_crop complete --epochs 200 --dataset mara --subset 2+encounters --backbone_pretraining savannah_elephants --backbone_lr 1e-4 --backbone_wd 1e-6 --print_every 5 --batch_size 64 --wandb_group MegaDescriptor_Mara_complete_sweep --wandb_name MD_mara_complete_lr1e-4_wd1e-6_e200"
# 13 : sbatch --parsable --job-name=MDc_13 --partition=vision-beery --qos=vision-beery-main --account=vision-beery --time=7-0:00:00 --mem=64G --gres=gpu:1 --chdir=/data/vision/beery/scratch/antoine/CBM_reid --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/MD_mara_complete_lr1e-5_wd1e-3_e200.%j.out --wrap="python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name PretrainMegaDescriptor --mega_descriptor_mode finetuning --mega_descriptor_crop complete --epochs 200 --dataset mara --subset 2+encounters --backbone_pretraining savannah_elephants --backbone_lr 1e-5 --backbone_wd 1e-3 --print_every 5 --batch_size 64 --wandb_group MegaDescriptor_Mara_complete_sweep --wandb_name MD_mara_complete_lr1e-5_wd1e-3_e200"
# 14 : sbatch --parsable --job-name=MDc_14 --partition=vision-beery --qos=vision-beery-main --account=vision-beery --time=7-0:00:00 --mem=64G --gres=gpu:1 --chdir=/data/vision/beery/scratch/antoine/CBM_reid --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/MD_mara_complete_lr1e-5_wd1e-4_e200.%j.out --wrap="python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name PretrainMegaDescriptor --mega_descriptor_mode finetuning --mega_descriptor_crop complete --epochs 200 --dataset mara --subset 2+encounters --backbone_pretraining savannah_elephants --backbone_lr 1e-5 --backbone_wd 1e-4 --print_every 5 --batch_size 64 --wandb_group MegaDescriptor_Mara_complete_sweep --wandb_name MD_mara_complete_lr1e-5_wd1e-4_e200"
# 15 : sbatch --parsable --job-name=MDc_15 --partition=vision-beery --qos=vision-beery-main --account=vision-beery --time=7-0:00:00 --mem=64G --gres=gpu:1 --chdir=/data/vision/beery/scratch/antoine/CBM_reid --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/MD_mara_complete_lr1e-5_wd1e-5_e200.%j.out --wrap="python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name PretrainMegaDescriptor --mega_descriptor_mode finetuning --mega_descriptor_crop complete --epochs 200 --dataset mara --subset 2+encounters --backbone_pretraining savannah_elephants --backbone_lr 1e-5 --backbone_wd 1e-5 --print_every 5 --batch_size 64 --wandb_group MegaDescriptor_Mara_complete_sweep --wandb_name MD_mara_complete_lr1e-5_wd1e-5_e200"
# 16 : sbatch --parsable --job-name=MDc_16 --partition=vision-beery --qos=vision-beery-main --account=vision-beery --time=7-0:00:00 --mem=64G --gres=gpu:1 --chdir=/data/vision/beery/scratch/antoine/CBM_reid --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/MD_mara_complete_lr1e-5_wd1e-6_e200.%j.out --wrap="python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name PretrainMegaDescriptor --mega_descriptor_mode finetuning --mega_descriptor_crop complete --epochs 200 --dataset mara --subset 2+encounters --backbone_pretraining savannah_elephants --backbone_lr 1e-5 --backbone_wd 1e-6 --print_every 5 --batch_size 64 --wandb_group MegaDescriptor_Mara_complete_sweep --wandb_name MD_mara_complete_lr1e-5_wd1e-6_e200"

# Left ear crop
# 01 : sbatch --parsable --job-name=MDl_01 --partition=vision-beery --qos=vision-beery-main --account=vision-beery --time=7-0:00:00 --mem=64G --gres=gpu:1 --chdir=/data/vision/beery/scratch/antoine/CBM_reid --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/MD_mara_left_ear_lr1e-2_wd1e-3_e200.%j.out --wrap="python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name PretrainMegaDescriptor --mega_descriptor_mode finetuning --mega_descriptor_crop left_ear --epochs 200 --dataset mara --subset 2+encounters --backbone_pretraining savannah_elephants --backbone_lr 1e-2 --backbone_wd 1e-3 --print_every 5 --batch_size 64 --wandb_group MegaDescriptor_Mara_left_ear_sweep --wandb_name MD_mara_left_ear_lr1e-2_wd1e-3_e200"
# 02 : sbatch --parsable --job-name=MDl_02 --partition=vision-beery --qos=vision-beery-main --account=vision-beery --time=7-0:00:00 --mem=64G --gres=gpu:1 --chdir=/data/vision/beery/scratch/antoine/CBM_reid --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/MD_mara_left_ear_lr1e-2_wd1e-4_e200.%j.out --wrap="python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name PretrainMegaDescriptor --mega_descriptor_mode finetuning --mega_descriptor_crop left_ear --epochs 200 --dataset mara --subset 2+encounters --backbone_pretraining savannah_elephants --backbone_lr 1e-2 --backbone_wd 1e-4 --print_every 5 --batch_size 64 --wandb_group MegaDescriptor_Mara_left_ear_sweep --wandb_name MD_mara_left_ear_lr1e-2_wd1e-4_e200"
# 03 : sbatch --parsable --job-name=MDl_03 --partition=vision-beery --qos=vision-beery-main --account=vision-beery --time=7-0:00:00 --mem=64G --gres=gpu:1 --chdir=/data/vision/beery/scratch/antoine/CBM_reid --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/MD_mara_left_ear_lr1e-2_wd1e-5_e200.%j.out --wrap="python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name PretrainMegaDescriptor --mega_descriptor_mode finetuning --mega_descriptor_crop left_ear --epochs 200 --dataset mara --subset 2+encounters --backbone_pretraining savannah_elephants --backbone_lr 1e-2 --backbone_wd 1e-5 --print_every 5 --batch_size 64 --wandb_group MegaDescriptor_Mara_left_ear_sweep --wandb_name MD_mara_left_ear_lr1e-2_wd1e-5_e200"
# 04 : sbatch --parsable --job-name=MDl_04 --partition=vision-beery --qos=vision-beery-main --account=vision-beery --time=7-0:00:00 --mem=64G --gres=gpu:1 --chdir=/data/vision/beery/scratch/antoine/CBM_reid --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/MD_mara_left_ear_lr1e-2_wd1e-6_e200.%j.out --wrap="python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name PretrainMegaDescriptor --mega_descriptor_mode finetuning --mega_descriptor_crop left_ear --epochs 200 --dataset mara --subset 2+encounters --backbone_pretraining savannah_elephants --backbone_lr 1e-2 --backbone_wd 1e-6 --print_every 5 --batch_size 64 --wandb_group MegaDescriptor_Mara_left_ear_sweep --wandb_name MD_mara_left_ear_lr1e-2_wd1e-6_e200"
# 05 : sbatch --parsable --job-name=MDl_05 --partition=vision-beery --qos=vision-beery-main --account=vision-beery --time=7-0:00:00 --mem=64G --gres=gpu:1 --chdir=/data/vision/beery/scratch/antoine/CBM_reid --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/MD_mara_left_ear_lr1e-3_wd1e-3_e200.%j.out --wrap="python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name PretrainMegaDescriptor --mega_descriptor_mode finetuning --mega_descriptor_crop left_ear --epochs 200 --dataset mara --subset 2+encounters --backbone_pretraining savannah_elephants --backbone_lr 1e-3 --backbone_wd 1e-3 --print_every 5 --batch_size 64 --wandb_group MegaDescriptor_Mara_left_ear_sweep --wandb_name MD_mara_left_ear_lr1e-3_wd1e-3_e200"
# 06 : sbatch --parsable --job-name=MDl_06 --partition=vision-beery --qos=vision-beery-main --account=vision-beery --time=7-0:00:00 --mem=64G --gres=gpu:1 --chdir=/data/vision/beery/scratch/antoine/CBM_reid --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/MD_mara_left_ear_lr1e-3_wd1e-4_e200.%j.out --wrap="python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name PretrainMegaDescriptor --mega_descriptor_mode finetuning --mega_descriptor_crop left_ear --epochs 200 --dataset mara --subset 2+encounters --backbone_pretraining savannah_elephants --backbone_lr 1e-3 --backbone_wd 1e-4 --print_every 5 --batch_size 64 --wandb_group MegaDescriptor_Mara_left_ear_sweep --wandb_name MD_mara_left_ear_lr1e-3_wd1e-4_e200"
# 07 : sbatch --parsable --job-name=MDl_07 --partition=vision-beery --qos=vision-beery-main --account=vision-beery --time=7-0:00:00 --mem=64G --gres=gpu:1 --chdir=/data/vision/beery/scratch/antoine/CBM_reid --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/MD_mara_left_ear_lr1e-3_wd1e-5_e200.%j.out --wrap="python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name PretrainMegaDescriptor --mega_descriptor_mode finetuning --mega_descriptor_crop left_ear --epochs 200 --dataset mara --subset 2+encounters --backbone_pretraining savannah_elephants --backbone_lr 1e-3 --backbone_wd 1e-5 --print_every 5 --batch_size 64 --wandb_group MegaDescriptor_Mara_left_ear_sweep --wandb_name MD_mara_left_ear_lr1e-3_wd1e-5_e200"
# 08 : sbatch --parsable --job-name=MDl_08 --partition=vision-beery --qos=vision-beery-main --account=vision-beery --time=7-0:00:00 --mem=64G --gres=gpu:1 --chdir=/data/vision/beery/scratch/antoine/CBM_reid --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/MD_mara_left_ear_lr1e-3_wd1e-6_e200.%j.out --wrap="python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name PretrainMegaDescriptor --mega_descriptor_mode finetuning --mega_descriptor_crop left_ear --epochs 200 --dataset mara --subset 2+encounters --backbone_pretraining savannah_elephants --backbone_lr 1e-3 --backbone_wd 1e-6 --print_every 5 --batch_size 64 --wandb_group MegaDescriptor_Mara_left_ear_sweep --wandb_name MD_mara_left_ear_lr1e-3_wd1e-6_e200"
# 09 : sbatch --parsable --job-name=MDl_09 --partition=vision-beery --qos=vision-beery-main --account=vision-beery --time=7-0:00:00 --mem=64G --gres=gpu:1 --chdir=/data/vision/beery/scratch/antoine/CBM_reid --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/MD_mara_left_ear_lr1e-4_wd1e-3_e200.%j.out --wrap="python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name PretrainMegaDescriptor --mega_descriptor_mode finetuning --mega_descriptor_crop left_ear --epochs 200 --dataset mara --subset 2+encounters --backbone_pretraining savannah_elephants --backbone_lr 1e-4 --backbone_wd 1e-3 --print_every 5 --batch_size 64 --wandb_group MegaDescriptor_Mara_left_ear_sweep --wandb_name MD_mara_left_ear_lr1e-4_wd1e-3_e200"
# 10 : sbatch --parsable --job-name=MDl_10 --partition=vision-beery --qos=vision-beery-main --account=vision-beery --time=7-0:00:00 --mem=64G --gres=gpu:1 --chdir=/data/vision/beery/scratch/antoine/CBM_reid --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/MD_mara_left_ear_lr1e-4_wd1e-4_e200.%j.out --wrap="python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name PretrainMegaDescriptor --mega_descriptor_mode finetuning --mega_descriptor_crop left_ear --epochs 200 --dataset mara --subset 2+encounters --backbone_pretraining savannah_elephants --backbone_lr 1e-4 --backbone_wd 1e-4 --print_every 5 --batch_size 64 --wandb_group MegaDescriptor_Mara_left_ear_sweep --wandb_name MD_mara_left_ear_lr1e-4_wd1e-4_e200"
# 11 : sbatch --parsable --job-name=MDl_11 --partition=vision-beery --qos=vision-beery-main --account=vision-beery --time=7-0:00:00 --mem=64G --gres=gpu:1 --chdir=/data/vision/beery/scratch/antoine/CBM_reid --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/MD_mara_left_ear_lr1e-4_wd1e-5_e200.%j.out --wrap="python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name PretrainMegaDescriptor --mega_descriptor_mode finetuning --mega_descriptor_crop left_ear --epochs 200 --dataset mara --subset 2+encounters --backbone_pretraining savannah_elephants --backbone_lr 1e-4 --backbone_wd 1e-5 --print_every 5 --batch_size 64 --wandb_group MegaDescriptor_Mara_left_ear_sweep --wandb_name MD_mara_left_ear_lr1e-4_wd1e-5_e200"
# 12 : sbatch --parsable --job-name=MDl_12 --partition=vision-beery --qos=vision-beery-main --account=vision-beery --time=7-0:00:00 --mem=64G --gres=gpu:1 --chdir=/data/vision/beery/scratch/antoine/CBM_reid --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/MD_mara_left_ear_lr1e-4_wd1e-6_e200.%j.out --wrap="python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name PretrainMegaDescriptor --mega_descriptor_mode finetuning --mega_descriptor_crop left_ear --epochs 200 --dataset mara --subset 2+encounters --backbone_pretraining savannah_elephants --backbone_lr 1e-4 --backbone_wd 1e-6 --print_every 5 --batch_size 64 --wandb_group MegaDescriptor_Mara_left_ear_sweep --wandb_name MD_mara_left_ear_lr1e-4_wd1e-6_e200"
# 13 : sbatch --parsable --job-name=MDl_13 --partition=vision-beery --qos=vision-beery-main --account=vision-beery --time=7-0:00:00 --mem=64G --gres=gpu:1 --chdir=/data/vision/beery/scratch/antoine/CBM_reid --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/MD_mara_left_ear_lr1e-5_wd1e-3_e200.%j.out --wrap="python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name PretrainMegaDescriptor --mega_descriptor_mode finetuning --mega_descriptor_crop left_ear --epochs 200 --dataset mara --subset 2+encounters --backbone_pretraining savannah_elephants --backbone_lr 1e-5 --backbone_wd 1e-3 --print_every 5 --batch_size 64 --wandb_group MegaDescriptor_Mara_left_ear_sweep --wandb_name MD_mara_left_ear_lr1e-5_wd1e-3_e200"
# 14 : sbatch --parsable --job-name=MDl_14 --partition=vision-beery --qos=vision-beery-main --account=vision-beery --time=7-0:00:00 --mem=64G --gres=gpu:1 --chdir=/data/vision/beery/scratch/antoine/CBM_reid --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/MD_mara_left_ear_lr1e-5_wd1e-4_e200.%j.out --wrap="python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name PretrainMegaDescriptor --mega_descriptor_mode finetuning --mega_descriptor_crop left_ear --epochs 200 --dataset mara --subset 2+encounters --backbone_pretraining savannah_elephants --backbone_lr 1e-5 --backbone_wd 1e-4 --print_every 5 --batch_size 64 --wandb_group MegaDescriptor_Mara_left_ear_sweep --wandb_name MD_mara_left_ear_lr1e-5_wd1e-4_e200"
# 15 : sbatch --parsable --job-name=MDl_15 --partition=vision-beery --qos=vision-beery-main --account=vision-beery --time=7-0:00:00 --mem=64G --gres=gpu:1 --chdir=/data/vision/beery/scratch/antoine/CBM_reid --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/MD_mara_left_ear_lr1e-5_wd1e-5_e200.%j.out --wrap="python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name PretrainMegaDescriptor --mega_descriptor_mode finetuning --mega_descriptor_crop left_ear --epochs 200 --dataset mara --subset 2+encounters --backbone_pretraining savannah_elephants --backbone_lr 1e-5 --backbone_wd 1e-5 --print_every 5 --batch_size 64 --wandb_group MegaDescriptor_Mara_left_ear_sweep --wandb_name MD_mara_left_ear_lr1e-5_wd1e-5_e200"
# 16 : sbatch --parsable --job-name=MDl_16 --partition=vision-beery --qos=vision-beery-main --account=vision-beery --time=7-0:00:00 --mem=64G --gres=gpu:1 --chdir=/data/vision/beery/scratch/antoine/CBM_reid --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/MD_mara_left_ear_lr1e-5_wd1e-6_e200.%j.out --wrap="python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name PretrainMegaDescriptor --mega_descriptor_mode finetuning --mega_descriptor_crop left_ear --epochs 200 --dataset mara --subset 2+encounters --backbone_pretraining savannah_elephants --backbone_lr 1e-5 --backbone_wd 1e-6 --print_every 5 --batch_size 64 --wandb_group MegaDescriptor_Mara_left_ear_sweep --wandb_name MD_mara_left_ear_lr1e-5_wd1e-6_e200"

# Right ear crop
# 01 : sbatch --parsable --job-name=MDr_01 --partition=vision-beery --qos=vision-beery-main --account=vision-beery --time=7-0:00:00 --mem=64G --gres=gpu:1 --chdir=/data/vision/beery/scratch/antoine/CBM_reid --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/MD_mara_right_ear_lr1e-2_wd1e-3_e200.%j.out --wrap="python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name PretrainMegaDescriptor --mega_descriptor_mode finetuning --mega_descriptor_crop right_ear --epochs 200 --dataset mara --subset 2+encounters --backbone_pretraining savannah_elephants --backbone_lr 1e-2 --backbone_wd 1e-3 --print_every 5 --batch_size 64 --wandb_group MegaDescriptor_Mara_right_ear_sweep --wandb_name MD_mara_right_ear_lr1e-2_wd1e-3_e200"
# 02 : sbatch --parsable --job-name=MDr_02 --partition=vision-beery --qos=vision-beery-main --account=vision-beery --time=7-0:00:00 --mem=64G --gres=gpu:1 --chdir=/data/vision/beery/scratch/antoine/CBM_reid --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/MD_mara_right_ear_lr1e-2_wd1e-4_e200.%j.out --wrap="python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name PretrainMegaDescriptor --mega_descriptor_mode finetuning --mega_descriptor_crop right_ear --epochs 200 --dataset mara --subset 2+encounters --backbone_pretraining savannah_elephants --backbone_lr 1e-2 --backbone_wd 1e-4 --print_every 5 --batch_size 64 --wandb_group MegaDescriptor_Mara_right_ear_sweep --wandb_name MD_mara_right_ear_lr1e-2_wd1e-4_e200"
# 03 : sbatch --parsable --job-name=MDr_03 --partition=vision-beery --qos=vision-beery-main --account=vision-beery --time=7-0:00:00 --mem=64G --gres=gpu:1 --chdir=/data/vision/beery/scratch/antoine/CBM_reid --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/MD_mara_right_ear_lr1e-2_wd1e-5_e200.%j.out --wrap="python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name PretrainMegaDescriptor --mega_descriptor_mode finetuning --mega_descriptor_crop right_ear --epochs 200 --dataset mara --subset 2+encounters --backbone_pretraining savannah_elephants --backbone_lr 1e-2 --backbone_wd 1e-5 --print_every 5 --batch_size 64 --wandb_group MegaDescriptor_Mara_right_ear_sweep --wandb_name MD_mara_right_ear_lr1e-2_wd1e-5_e200"
# 04 : sbatch --parsable --job-name=MDr_04 --partition=vision-beery --qos=vision-beery-main --account=vision-beery --time=7-0:00:00 --mem=64G --gres=gpu:1 --chdir=/data/vision/beery/scratch/antoine/CBM_reid --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/MD_mara_right_ear_lr1e-2_wd1e-6_e200.%j.out --wrap="python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name PretrainMegaDescriptor --mega_descriptor_mode finetuning --mega_descriptor_crop right_ear --epochs 200 --dataset mara --subset 2+encounters --backbone_pretraining savannah_elephants --backbone_lr 1e-2 --backbone_wd 1e-6 --print_every 5 --batch_size 64 --wandb_group MegaDescriptor_Mara_right_ear_sweep --wandb_name MD_mara_right_ear_lr1e-2_wd1e-6_e200"
# 05 : sbatch --parsable --job-name=MDr_05 --partition=vision-beery --qos=vision-beery-main --account=vision-beery --time=7-0:00:00 --mem=64G --gres=gpu:1 --chdir=/data/vision/beery/scratch/antoine/CBM_reid --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/MD_mara_right_ear_lr1e-3_wd1e-3_e200.%j.out --wrap="python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name PretrainMegaDescriptor --mega_descriptor_mode finetuning --mega_descriptor_crop right_ear --epochs 200 --dataset mara --subset 2+encounters --backbone_pretraining savannah_elephants --backbone_lr 1e-3 --backbone_wd 1e-3 --print_every 5 --batch_size 64 --wandb_group MegaDescriptor_Mara_right_ear_sweep --wandb_name MD_mara_right_ear_lr1e-3_wd1e-3_e200"
# 06 : sbatch --parsable --job-name=MDr_06 --partition=vision-beery --qos=vision-beery-main --account=vision-beery --time=7-0:00:00 --mem=64G --gres=gpu:1 --chdir=/data/vision/beery/scratch/antoine/CBM_reid --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/MD_mara_right_ear_lr1e-3_wd1e-4_e200.%j.out --wrap="python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name PretrainMegaDescriptor --mega_descriptor_mode finetuning --mega_descriptor_crop right_ear --epochs 200 --dataset mara --subset 2+encounters --backbone_pretraining savannah_elephants --backbone_lr 1e-3 --backbone_wd 1e-4 --print_every 5 --batch_size 64 --wandb_group MegaDescriptor_Mara_right_ear_sweep --wandb_name MD_mara_right_ear_lr1e-3_wd1e-4_e200"
# 07 : sbatch --parsable --job-name=MDr_07 --partition=vision-beery --qos=vision-beery-main --account=vision-beery --time=7-0:00:00 --mem=64G --gres=gpu:1 --chdir=/data/vision/beery/scratch/antoine/CBM_reid --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/MD_mara_right_ear_lr1e-3_wd1e-5_e200.%j.out --wrap="python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name PretrainMegaDescriptor --mega_descriptor_mode finetuning --mega_descriptor_crop right_ear --epochs 200 --dataset mara --subset 2+encounters --backbone_pretraining savannah_elephants --backbone_lr 1e-3 --backbone_wd 1e-5 --print_every 5 --batch_size 64 --wandb_group MegaDescriptor_Mara_right_ear_sweep --wandb_name MD_mara_right_ear_lr1e-3_wd1e-5_e200"
# 08 : sbatch --parsable --job-name=MDr_08 --partition=vision-beery --qos=vision-beery-main --account=vision-beery --time=7-0:00:00 --mem=64G --gres=gpu:1 --chdir=/data/vision/beery/scratch/antoine/CBM_reid --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/MD_mara_right_ear_lr1e-3_wd1e-6_e200.%j.out --wrap="python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name PretrainMegaDescriptor --mega_descriptor_mode finetuning --mega_descriptor_crop right_ear --epochs 200 --dataset mara --subset 2+encounters --backbone_pretraining savannah_elephants --backbone_lr 1e-3 --backbone_wd 1e-6 --print_every 5 --batch_size 64 --wandb_group MegaDescriptor_Mara_right_ear_sweep --wandb_name MD_mara_right_ear_lr1e-3_wd1e-6_e200"
# 09 : sbatch --parsable --job-name=MDr_09 --partition=vision-beery --qos=vision-beery-main --account=vision-beery --time=7-0:00:00 --mem=64G --gres=gpu:1 --chdir=/data/vision/beery/scratch/antoine/CBM_reid --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/MD_mara_right_ear_lr1e-4_wd1e-3_e200.%j.out --wrap="python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name PretrainMegaDescriptor --mega_descriptor_mode finetuning --mega_descriptor_crop right_ear --epochs 200 --dataset mara --subset 2+encounters --backbone_pretraining savannah_elephants --backbone_lr 1e-4 --backbone_wd 1e-3 --print_every 5 --batch_size 64 --wandb_group MegaDescriptor_Mara_right_ear_sweep --wandb_name MD_mara_right_ear_lr1e-4_wd1e-3_e200"
# 10 : sbatch --parsable --job-name=MDr_10 --partition=vision-beery --qos=vision-beery-main --account=vision-beery --time=7-0:00:00 --mem=64G --gres=gpu:1 --chdir=/data/vision/beery/scratch/antoine/CBM_reid --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/MD_mara_right_ear_lr1e-4_wd1e-4_e200.%j.out --wrap="python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name PretrainMegaDescriptor --mega_descriptor_mode finetuning --mega_descriptor_crop right_ear --epochs 200 --dataset mara --subset 2+encounters --backbone_pretraining savannah_elephants --backbone_lr 1e-4 --backbone_wd 1e-4 --print_every 5 --batch_size 64 --wandb_group MegaDescriptor_Mara_right_ear_sweep --wandb_name MD_mara_right_ear_lr1e-4_wd1e-4_e200"
# 11 : sbatch --parsable --job-name=MDr_11 --partition=vision-beery --qos=vision-beery-main --account=vision-beery --time=7-0:00:00 --mem=64G --gres=gpu:1 --chdir=/data/vision/beery/scratch/antoine/CBM_reid --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/MD_mara_right_ear_lr1e-4_wd1e-5_e200.%j.out --wrap="python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name PretrainMegaDescriptor --mega_descriptor_mode finetuning --mega_descriptor_crop right_ear --epochs 200 --dataset mara --subset 2+encounters --backbone_pretraining savannah_elephants --backbone_lr 1e-4 --backbone_wd 1e-5 --print_every 5 --batch_size 64 --wandb_group MegaDescriptor_Mara_right_ear_sweep --wandb_name MD_mara_right_ear_lr1e-4_wd1e-5_e200"
# 12 : sbatch --parsable --job-name=MDr_12 --partition=vision-beery --qos=vision-beery-main --account=vision-beery --time=7-0:00:00 --mem=64G --gres=gpu:1 --chdir=/data/vision/beery/scratch/antoine/CBM_reid --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/MD_mara_right_ear_lr1e-4_wd1e-6_e200.%j.out --wrap="python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name PretrainMegaDescriptor --mega_descriptor_mode finetuning --mega_descriptor_crop right_ear --epochs 200 --dataset mara --subset 2+encounters --backbone_pretraining savannah_elephants --backbone_lr 1e-4 --backbone_wd 1e-6 --print_every 5 --batch_size 64 --wandb_group MegaDescriptor_Mara_right_ear_sweep --wandb_name MD_mara_right_ear_lr1e-4_wd1e-6_e200"
# 13 : sbatch --parsable --job-name=MDr_13 --partition=vision-beery --qos=vision-beery-main --account=vision-beery --time=7-0:00:00 --mem=64G --gres=gpu:1 --chdir=/data/vision/beery/scratch/antoine/CBM_reid --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/MD_mara_right_ear_lr1e-5_wd1e-3_e200.%j.out --wrap="python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name PretrainMegaDescriptor --mega_descriptor_mode finetuning --mega_descriptor_crop right_ear --epochs 200 --dataset mara --subset 2+encounters --backbone_pretraining savannah_elephants --backbone_lr 1e-5 --backbone_wd 1e-3 --print_every 5 --batch_size 64 --wandb_group MegaDescriptor_Mara_right_ear_sweep --wandb_name MD_mara_right_ear_lr1e-5_wd1e-3_e200"
# 14 : sbatch --parsable --job-name=MDr_14 --partition=vision-beery --qos=vision-beery-main --account=vision-beery --time=7-0:00:00 --mem=64G --gres=gpu:1 --chdir=/data/vision/beery/scratch/antoine/CBM_reid --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/MD_mara_right_ear_lr1e-5_wd1e-4_e200.%j.out --wrap="python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name PretrainMegaDescriptor --mega_descriptor_mode finetuning --mega_descriptor_crop right_ear --epochs 200 --dataset mara --subset 2+encounters --backbone_pretraining savannah_elephants --backbone_lr 1e-5 --backbone_wd 1e-4 --print_every 5 --batch_size 64 --wandb_group MegaDescriptor_Mara_right_ear_sweep --wandb_name MD_mara_right_ear_lr1e-5_wd1e-4_e200"
# 15 : sbatch --parsable --job-name=MDr_15 --partition=vision-beery --qos=vision-beery-main --account=vision-beery --time=7-0:00:00 --mem=64G --gres=gpu:1 --chdir=/data/vision/beery/scratch/antoine/CBM_reid --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/MD_mara_right_ear_lr1e-5_wd1e-5_e200.%j.out --wrap="python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name PretrainMegaDescriptor --mega_descriptor_mode finetuning --mega_descriptor_crop right_ear --epochs 200 --dataset mara --subset 2+encounters --backbone_pretraining savannah_elephants --backbone_lr 1e-5 --backbone_wd 1e-5 --print_every 5 --batch_size 64 --wandb_group MegaDescriptor_Mara_right_ear_sweep --wandb_name MD_mara_right_ear_lr1e-5_wd1e-5_e200"
# 16 : sbatch --parsable --job-name=MDr_16 --partition=vision-beery --qos=vision-beery-main --account=vision-beery --time=7-0:00:00 --mem=64G --gres=gpu:1 --chdir=/data/vision/beery/scratch/antoine/CBM_reid --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/MD_mara_right_ear_lr1e-5_wd1e-6_e200.%j.out --wrap="python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name PretrainMegaDescriptor --mega_descriptor_mode finetuning --mega_descriptor_crop right_ear --epochs 200 --dataset mara --subset 2+encounters --backbone_pretraining savannah_elephants --backbone_lr 1e-5 --backbone_wd 1e-6 --print_every 5 --batch_size 64 --wandb_group MegaDescriptor_Mara_right_ear_sweep --wandb_name MD_mara_right_ear_lr1e-5_wd1e-6_e200"
