#!/bin/bash
#SBATCH --job-name=cbm-reid-megadescriptor
#SBATCH --partition=vision-beery
#SBATCH --qos=vision-beery-main
#SBATCH --account=vision-beery
##SBATCH --requeue

#SBATCH --time=2-0:00:00
#SBATCH --mem=64G
#SBATCH --gres=gpu:1
#SBATCH --output=/data/vision/beery/scratch/antoine/CBM_reid/bash/slurm_logs/projector.%j.out
#SBATCH --chdir=/data/vision/beery/scratch/antoine/CBM_reid

set -euo pipefail


# SWEEP 1: Sequential + alpha learnable, 100% correction at training. lr in {1e-3, 1e-4, 1e-5} x wd in {1e-4, 1e-5, 1e-6}
# 17 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training sighting_1.0 --alpha 0.5 --alpha_learnable True --projector_training_policy sequential --projector_lr 1e-3 --projector_wd 1e-4 --layer_norm True --print_every 10 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_sweep_seq_learned_alpha_100cor --wandb_name SeqLearned_100cor_lr1e-3_wd1e-4
# 18 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training sighting_1.0 --alpha 0.5 --alpha_learnable True --projector_training_policy sequential --projector_lr 1e-3 --projector_wd 1e-5 --layer_norm True --print_every 10 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_sweep_seq_learned_alpha_100cor --wandb_name SeqLearned_100cor_lr1e-3_wd1e-5
# 19 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training sighting_1.0 --alpha 0.5 --alpha_learnable True --projector_training_policy sequential --projector_lr 1e-3 --projector_wd 1e-6 --layer_norm True --print_every 10 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_sweep_seq_learned_alpha_100cor --wandb_name SeqLearned_100cor_lr1e-3_wd1e-6
# 20 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training sighting_1.0 --alpha 0.5 --alpha_learnable True --projector_training_policy sequential --projector_lr 1e-4 --projector_wd 1e-4 --layer_norm True --print_every 10 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_sweep_seq_learned_alpha_100cor --wandb_name SeqLearned_100cor_lr1e-4_wd1e-4
# 21 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training sighting_1.0 --alpha 0.5 --alpha_learnable True --projector_training_policy sequential --projector_lr 1e-4 --projector_wd 1e-5 --layer_norm True --print_every 10 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_sweep_seq_learned_alpha_100cor --wandb_name SeqLearned_100cor_lr1e-4_wd1e-5
# 22 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training sighting_1.0 --alpha 0.5 --alpha_learnable True --projector_training_policy sequential --projector_lr 1e-4 --projector_wd 1e-6 --layer_norm True --print_every 10 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_sweep_seq_learned_alpha_100cor --wandb_name SeqLearned_100cor_lr1e-4_wd1e-6
# 23 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training sighting_1.0 --alpha 0.5 --alpha_learnable True --projector_training_policy sequential --projector_lr 1e-5 --projector_wd 1e-4 --layer_norm True --print_every 10 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_sweep_seq_learned_alpha_100cor --wandb_name SeqLearned_100cor_lr1e-5_wd1e-4
# 24 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training sighting_1.0 --alpha 0.5 --alpha_learnable True --projector_training_policy sequential --projector_lr 1e-5 --projector_wd 1e-5 --layer_norm True --print_every 10 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_sweep_seq_learned_alpha_100cor --wandb_name SeqLearned_100cor_lr1e-5_wd1e-5
# 25 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training sighting_1.0 --alpha 0.5 --alpha_learnable True --projector_training_policy sequential --projector_lr 1e-5 --projector_wd 1e-6 --layer_norm True --print_every 10 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_sweep_seq_learned_alpha_100cor --wandb_name SeqLearned_100cor_lr1e-5_wd1e-6

# SWEEP 2: Sequential + alpha fixed to 0.5, 100% correction at training. lr in {1e-3, 1e-4, 1e-5} x wd in {1e-4, 1e-5, 1e-6}
# 26 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training sighting_1.0 --alpha 0.5 --alpha_learnable False --projector_training_policy sequential --projector_lr 1e-3 --projector_wd 1e-4 --layer_norm False --print_every 10 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_sweep_seq_fixed_alpha_100cor --wandb_name SeqFixed_100cor_lr1e-3_wd1e-4
# 27 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training sighting_1.0 --alpha 0.5 --alpha_learnable False --projector_training_policy sequential --projector_lr 1e-3 --projector_wd 1e-5 --layer_norm False --print_every 10 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_sweep_seq_fixed_alpha_100cor --wandb_name SeqFixed_100cor_lr1e-3_wd1e-5
# 28 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training sighting_1.0 --alpha 0.5 --alpha_learnable False --projector_training_policy sequential --projector_lr 1e-3 --projector_wd 1e-6 --layer_norm False --print_every 10 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_sweep_seq_fixed_alpha_100cor --wandb_name SeqFixed_100cor_lr1e-3_wd1e-6
# 29 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training sighting_1.0 --alpha 0.5 --alpha_learnable False --projector_training_policy sequential --projector_lr 1e-4 --projector_wd 1e-4 --layer_norm False --print_every 10 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_sweep_seq_fixed_alpha_100cor --wandb_name SeqFixed_100cor_lr1e-4_wd1e-4
# 30 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training sighting_1.0 --alpha 0.5 --alpha_learnable False --projector_training_policy sequential --projector_lr 1e-4 --projector_wd 1e-5 --layer_norm False --print_every 10 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_sweep_seq_fixed_alpha_100cor --wandb_name SeqFixed_100cor_lr1e-4_wd1e-5
# 31 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training sighting_1.0 --alpha 0.5 --alpha_learnable False --projector_training_policy sequential --projector_lr 1e-4 --projector_wd 1e-6 --layer_norm False --print_every 10 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_sweep_seq_fixed_alpha_100cor --wandb_name SeqFixed_100cor_lr1e-4_wd1e-6
# 32 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training sighting_1.0 --alpha 0.5 --alpha_learnable False --projector_training_policy sequential --projector_lr 1e-5 --projector_wd 1e-4 --layer_norm False --print_every 10 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_sweep_seq_fixed_alpha_100cor --wandb_name SeqFixed_100cor_lr1e-5_wd1e-4
# 33 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training sighting_1.0 --alpha 0.5 --alpha_learnable False --projector_training_policy sequential --projector_lr 1e-5 --projector_wd 1e-5 --layer_norm False --print_every 10 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_sweep_seq_fixed_alpha_100cor --wandb_name SeqFixed_100cor_lr1e-5_wd1e-5
# 34 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training sighting_1.0 --alpha 0.5 --alpha_learnable False --projector_training_policy sequential --projector_lr 1e-5 --projector_wd 1e-6 --layer_norm False --print_every 10 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_sweep_seq_fixed_alpha_100cor --wandb_name SeqFixed_100cor_lr1e-5_wd1e-6

# SWEEP 3: Joint + alpha learnable, 100% correction at training. lr in {1e-3, 1e-4, 1e-5} x wd in {1e-4, 1e-5, 1e-6}
# 35 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training sighting_1.0 --alpha 0.5 --alpha_learnable True --projector_training_policy joint --projector_lr 1e-3 --projector_wd 1e-4 --layer_norm True --print_every 10 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_sweep_joint_learned_alpha_100cor --wandb_name JointLearned_100cor_lr1e-3_wd1e-4
# 36 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training sighting_1.0 --alpha 0.5 --alpha_learnable True --projector_training_policy joint --projector_lr 1e-3 --projector_wd 1e-5 --layer_norm True --print_every 10 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_sweep_joint_learned_alpha_100cor --wandb_name JointLearned_100cor_lr1e-3_wd1e-5
# 37 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training sighting_1.0 --alpha 0.5 --alpha_learnable True --projector_training_policy joint --projector_lr 1e-3 --projector_wd 1e-6 --layer_norm True --print_every 10 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_sweep_joint_learned_alpha_100cor --wandb_name JointLearned_100cor_lr1e-3_wd1e-6
# 38 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training sighting_1.0 --alpha 0.5 --alpha_learnable True --projector_training_policy joint --projector_lr 1e-4 --projector_wd 1e-4 --layer_norm True --print_every 10 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_sweep_joint_learned_alpha_100cor --wandb_name JointLearned_100cor_lr1e-4_wd1e-4
# 39 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training sighting_1.0 --alpha 0.5 --alpha_learnable True --projector_training_policy joint --projector_lr 1e-4 --projector_wd 1e-5 --layer_norm True --print_every 10 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_sweep_joint_learned_alpha_100cor --wandb_name JointLearned_100cor_lr1e-4_wd1e-5
# 40 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training sighting_1.0 --alpha 0.5 --alpha_learnable True --projector_training_policy joint --projector_lr 1e-4 --projector_wd 1e-6 --layer_norm True --print_every 10 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_sweep_joint_learned_alpha_100cor --wandb_name JointLearned_100cor_lr1e-4_wd1e-6
# 41 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training sighting_1.0 --alpha 0.5 --alpha_learnable True --projector_training_policy joint --projector_lr 1e-5 --projector_wd 1e-4 --layer_norm True --print_every 10 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_sweep_joint_learned_alpha_100cor --wandb_name JointLearned_100cor_lr1e-5_wd1e-4
# 42 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training sighting_1.0 --alpha 0.5 --alpha_learnable True --projector_training_policy joint --projector_lr 1e-5 --projector_wd 1e-5 --layer_norm True --print_every 10 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_sweep_joint_learned_alpha_100cor --wandb_name JointLearned_100cor_lr1e-5_wd1e-5
# 43 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training sighting_1.0 --alpha 0.5 --alpha_learnable True --projector_training_policy joint --projector_lr 1e-5 --projector_wd 1e-6 --layer_norm True --print_every 10 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_sweep_joint_learned_alpha_100cor --wandb_name JointLearned_100cor_lr1e-5_wd1e-6

# SWEEP 4: Joint + alpha fixed to 0.5, 100% correction at training. lr in {1e-3, 1e-4, 1e-5} x wd in {1e-4, 1e-5, 1e-6}
# 44 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training sighting_1.0 --alpha 0.5 --alpha_learnable False --projector_training_policy joint --projector_lr 1e-3 --projector_wd 1e-4 --layer_norm False --print_every 10 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_sweep_joint_fixed_alpha_100cor --wandb_name JointFixed_100cor_lr1e-3_wd1e-4
# 45 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training sighting_1.0 --alpha 0.5 --alpha_learnable False --projector_training_policy joint --projector_lr 1e-3 --projector_wd 1e-5 --layer_norm False --print_every 10 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_sweep_joint_fixed_alpha_100cor --wandb_name JointFixed_100cor_lr1e-3_wd1e-5
# 46 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training sighting_1.0 --alpha 0.5 --alpha_learnable False --projector_training_policy joint --projector_lr 1e-3 --projector_wd 1e-6 --layer_norm False --print_every 10 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_sweep_joint_fixed_alpha_100cor --wandb_name JointFixed_100cor_lr1e-3_wd1e-6
# 47 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training sighting_1.0 --alpha 0.5 --alpha_learnable False --projector_training_policy joint --projector_lr 1e-4 --projector_wd 1e-4 --layer_norm False --print_every 10 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_sweep_joint_fixed_alpha_100cor --wandb_name JointFixed_100cor_lr1e-4_wd1e-4
# 48 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training sighting_1.0 --alpha 0.5 --alpha_learnable False --projector_training_policy joint --projector_lr 1e-4 --projector_wd 1e-5 --layer_norm False --print_every 10 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_sweep_joint_fixed_alpha_100cor --wandb_name JointFixed_100cor_lr1e-4_wd1e-5
# 49 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training sighting_1.0 --alpha 0.5 --alpha_learnable False --projector_training_policy joint --projector_lr 1e-4 --projector_wd 1e-6 --layer_norm False --print_every 10 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_sweep_joint_fixed_alpha_100cor --wandb_name JointFixed_100cor_lr1e-4_wd1e-6
# 50 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training sighting_1.0 --alpha 0.5 --alpha_learnable False --projector_training_policy joint --projector_lr 1e-5 --projector_wd 1e-4 --layer_norm False --print_every 10 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_sweep_joint_fixed_alpha_100cor --wandb_name JointFixed_100cor_lr1e-5_wd1e-4
# 51 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training sighting_1.0 --alpha 0.5 --alpha_learnable False --projector_training_policy joint --projector_lr 1e-5 --projector_wd 1e-5 --layer_norm False --print_every 10 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_sweep_joint_fixed_alpha_100cor --wandb_name JointFixed_100cor_lr1e-5_wd1e-5
# 52 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training sighting_1.0 --alpha 0.5 --alpha_learnable False --projector_training_policy joint --projector_lr 1e-5 --projector_wd 1e-6 --layer_norm False --print_every 10 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_sweep_joint_fixed_alpha_100cor --wandb_name JointFixed_100cor_lr1e-5_wd1e-6

# BEST HYPERPARAM for 100% cor inference ARE
# for sequential + alpha fixed: lr=1e-3 and wd=1e-6
# for sequential + alpha learnable: lr=1e-4  and wd=1e-6 
# for joint + alpha fixed: lr = 1e-3 and wd = 1e-5
# for sequential + alpha fixed: lr=1e-3 and wd=1e-6


# Heatmap rerun: sighting-level training correction from 0% to 100%, with learned alpha.
# Projector checkpoints are selected only from epoch 10 onward.
# 01 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 300 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_normalized_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training sighting_0.0 --alpha 0.5 --alpha_learnable True --projector_training_policy sequential --projector_lr 1e-4 --projector_wd 1e-6 --layer_norm True --print_every 5 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_heatmap_three_alpha_learned_min10 --wandb_name Heatmap_three_00cor
# 02 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_normalized_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training sighting_0.1 --alpha 0.5 --alpha_learnable True --projector_training_policy sequential --projector_lr 1e-4 --projector_wd 1e-6 --layer_norm True --print_every 5 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_heatmap_three_alpha_learned_min10 --wandb_name Heatmap_three_10cor
# 03 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_normalized_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training sighting_0.2 --alpha 0.5 --alpha_learnable True --projector_training_policy sequential --projector_lr 1e-4 --projector_wd 1e-6 --layer_norm True --print_every 5 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_heatmap_three_alpha_learned_min10 --wandb_name Heatmap_three_20cor
# 04 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_normalized_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training sighting_0.3 --alpha 0.5 --alpha_learnable True --projector_training_policy sequential --projector_lr 1e-4 --projector_wd 1e-6 --layer_norm True --print_every 5 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_heatmap_three_alpha_learned_min10 --wandb_name Heatmap_three_30cor
# 05 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_normalized_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training sighting_0.4 --alpha 0.5 --alpha_learnable True --projector_training_policy sequential --projector_lr 1e-4 --projector_wd 1e-6 --layer_norm True --print_every 5 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_heatmap_three_alpha_learned_min10 --wandb_name Heatmap_three_40cor
# 06 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_normalized_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training sighting_0.5 --alpha 0.5 --alpha_learnable True --projector_training_policy sequential --projector_lr 1e-4 --projector_wd 1e-6 --layer_norm True --print_every 5 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_heatmap_three_alpha_learned_min10 --wandb_name Heatmap_three_50cor
# 07 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_normalized_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training sighting_0.6 --alpha 0.5 --alpha_learnable True --projector_training_policy sequential --projector_lr 1e-4 --projector_wd 1e-6 --layer_norm True --print_every 5 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_heatmap_three_alpha_learned_min10 --wandb_name Heatmap_three_60cor
# 08 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_normalized_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training sighting_0.7 --alpha 0.5 --alpha_learnable True --projector_training_policy sequential --projector_lr 1e-4 --projector_wd 1e-6 --layer_norm True --print_every 5 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_heatmap_three_alpha_learned_min10 --wandb_name Heatmap_three_70cor
# 09 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_normalized_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training sighting_0.8 --alpha 0.5 --alpha_learnable True --projector_training_policy sequential --projector_lr 1e-4 --projector_wd 1e-6 --layer_norm True --print_every 5 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_heatmap_three_alpha_learned_min10 --wandb_name Heatmap_three_80cor
# 10 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_normalized_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training sighting_0.9 --alpha 0.5 --alpha_learnable True --projector_training_policy sequential --projector_lr 1e-4 --projector_wd 1e-6 --layer_norm True --print_every 5 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_heatmap_three_alpha_learned_min10 --wandb_name Heatmap_three_90cor
# 11 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_normalized_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training sighting_1.0 --alpha 0.5 --alpha_learnable True --projector_training_policy sequential --projector_lr 1e-4 --projector_wd 1e-6 --layer_norm True --print_every 5 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_heatmap_three_alpha_learned_min10 --wandb_name Heatmap_three_100cor

# Heatmap rerun: image-level training correction from 10% to 100%, with learned alpha.
# Projector checkpoints are selected only from epoch 10 onward.
# 0% is shared with the sighting-level sweep, so there are only 10 new runs here.
# I01 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 300 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_normalized_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training image_0.1 --alpha 0.5 --alpha_learnable True --projector_training_policy sequential --projector_lr 1e-4 --projector_wd 1e-6 --layer_norm True --print_every 5 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_heatmap_three_alpha_learned_image_training_min10 --wandb_name Heatmap_three_image_10cor
# I02 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_normalized_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training image_0.2 --alpha 0.5 --alpha_learnable True --projector_training_policy sequential --projector_lr 1e-4 --projector_wd 1e-6 --layer_norm True --print_every 5 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_heatmap_three_alpha_learned_image_training_min10 --wandb_name Heatmap_three_image_20cor
# I03 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_normalized_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training image_0.3 --alpha 0.5 --alpha_learnable True --projector_training_policy sequential --projector_lr 1e-4 --projector_wd 1e-6 --layer_norm True --print_every 5 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_heatmap_three_alpha_learned_image_training_min10 --wandb_name Heatmap_three_image_30cor
# I04 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_normalized_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training image_0.4 --alpha 0.5 --alpha_learnable True --projector_training_policy sequential --projector_lr 1e-4 --projector_wd 1e-6 --layer_norm True --print_every 5 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_heatmap_three_alpha_learned_image_training_min10 --wandb_name Heatmap_three_image_40cor
# I05 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_normalized_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training image_0.5 --alpha 0.5 --alpha_learnable True --projector_training_policy sequential --projector_lr 1e-4 --projector_wd 1e-6 --layer_norm True --print_every 5 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_heatmap_three_alpha_learned_image_training_min10 --wandb_name Heatmap_three_image_50cor
# I06 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_normalized_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training image_0.6 --alpha 0.5 --alpha_learnable True --projector_training_policy sequential --projector_lr 1e-4 --projector_wd 1e-6 --layer_norm True --print_every 5 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_heatmap_three_alpha_learned_image_training_min10 --wandb_name Heatmap_three_image_60cor
# I07 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_normalized_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training image_0.7 --alpha 0.5 --alpha_learnable True --projector_training_policy sequential --projector_lr 1e-4 --projector_wd 1e-6 --layer_norm True --print_every 5 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_heatmap_three_alpha_learned_image_training_min10 --wandb_name Heatmap_three_image_70cor
# I08 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_normalized_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training image_0.8 --alpha 0.5 --alpha_learnable True --projector_training_policy sequential --projector_lr 1e-4 --projector_wd 1e-6 --layer_norm True --print_every 5 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_heatmap_three_alpha_learned_image_training_min10 --wandb_name Heatmap_three_image_80cor
# I09 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_normalized_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training image_0.9 --alpha 0.5 --alpha_learnable True --projector_training_policy sequential --projector_lr 1e-4 --projector_wd 1e-6 --layer_norm True --print_every 5 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_heatmap_three_alpha_learned_image_training_min10 --wandb_name Heatmap_three_image_90cor
# I10 : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_normalized_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training image_1.0 --alpha 0.5 --alpha_learnable True --projector_training_policy sequential --projector_lr 1e-4 --projector_wd 1e-6 --layer_norm True --print_every 5 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_heatmap_three_alpha_learned_image_training_min10 --wandb_name Heatmap_three_image_100cor

# Ablation: training={Seq, Joint} x alpha={fixed, learned}, using three concept-head architecture.
# Seq + fixed : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training sighting_0.5 --alpha 0.5 --alpha_learnable False --projector_training_policy sequential --projector_lr 1e-3 --projector_wd 1e-6 --layer_norm False --print_every 10 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_training_alpha_ablation_three --wandb_name Ablation_Seq_fixed_alpha
# Seq + learned : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training sighting_0.5 --alpha 0.5 --alpha_learnable True --projector_training_policy sequential --projector_lr 1e-4 --projector_wd 1e-6 --layer_norm True --print_every 10 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_training_alpha_ablation_three --wandb_name Ablation_Seq_learned_alpha
# Joint + fixed : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training sighting_0.5 --alpha 0.5 --alpha_learnable False --projector_training_policy joint --projector_lr 1e-3 --projector_wd 1e-5 --layer_norm False --print_every 10 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_training_alpha_ablation_three --wandb_name Ablation_Joint_fixed_alpha
# Joint + learned : python /data/vision/beery/scratch/antoine/CBM_reid/methods/run_experiment.py --pipeline_name CHAIR --epochs 150 --dataset mara --subset 2+encounters --backbone_for_concepts_pretraining backbone_for_concepts_three_gold --backbone_pretraining backbone_gold --concept_head_pretraining concept_head_three_gold --concept_head_architecture three --concept_head_target_is_ele_seek False --correction_at_training sighting_0.5 --alpha 0.5 --alpha_learnable True --projector_training_policy joint --projector_lr 1e-3 --projector_wd 1e-6 --layer_norm True --print_every 10 --batch_size 64 --save_best True --test_concept_head_before_projector True --wandb_group Projector_training_alpha_ablation_three --wandb_name Ablation_Joint_learned_alpha
